# примеры API-запросов

@baseUrl = http://localhost:8000/api

###

# создание объявления
# -- создвать объявление могут админы и пользователи
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 2c071f6b49703258910158cbe0699a8c2bdf4acf

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# просмотр объявлений
# -- выводятся только объявления, имеющие статус OPEN и CLOSED
# -- объявления со статусом DRAFT может вывести только их автор (по токену)
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# получение объявлений с фильтрацией по дате (created_at_after)
GET {{baseUrl}}/advertisements/?created_at_after=2023-06-30
Content-Type: application/json

###

# получение объявлений с фильтрацией по дате (created_at_before)
GET {{baseUrl}}/advertisements/?created_at_before=2023-06-30
Content-Type: application/json

###

# получение объявлений с фильтрацией по статусу
# -- выводятся только объявления, имеющие статус OPEN и CLOSED
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###

# получение объявлений с фильтрацией по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# обновление объявления 
# -- админы могут менять любые объявления
# -- пользователи могут менять только свое объявление
# -- /int/ - id объявления
PATCH  {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 2c071f6b49703258910158cbe0699a8c2bdf4acf

{
  "status": "DRAFT"
}

###

# получение объявлений из DRAFT (в обычном GET-запросе их нет)
# -- объявление показывается только его автору (по токену)
GET {{baseUrl}}/advertisements/?status=DRAFT
Content-Type: application/json
Authorization: Token 2c071f6b49703258910158cbe0699a8c2bdf4acf

###

# обновление объявления
# -- админы могут менять любые объявления
# -- пользователи могут менять только свое объявление
# -- /int/ - id объявления
PATCH  {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 2c071f6b49703258910158cbe0699a8c2bdf4acf

{
  "status": "OPEN"
}

###

# добавление объявления в избранные
# -- автор объявления не может добавить своё объявление в избранные
# -- /int/ - id объявления
POST {{baseUrl}}/advertisements/1/add_to_favorites/
Content-Type: application/json
Authorization: Token 8ae9ac82428229f90221b137bedcc56e46485b38

###

# получение списка всех собственных избранных объявлений
## -- выводит все объявления, которые автор добавил в избранные
GET {{baseUrl}}/advertisements/favorite_advertisements/
Content-Type: application/json
Authorization: Token 8ae9ac82428229f90221b137bedcc56e46485b38

###

# получение списка избранных объявлений по фильтрации
## -- фильтрация аналогична случаю {{baseUrl}}/advertisements/
GET {{baseUrl}}/advertisements/favorite_advertisements/?created_at_after=2023-06-30
Content-Type: application/json
Authorization: Token 8ae9ac82428229f90221b137bedcc56e46485b38

###

# удаление объявления из избранных
## -- удаляется только у автора избранного объявления
# -- /int/ - id объявления
DELETE {{baseUrl}}/advertisements/1/remove_from_favorites/
Content-Type: application/json
Authorization: Token 8ae9ac82428229f90221b137bedcc56e46485b38

###

# удаление объявления
# -- админы могут удалять любые объявления
# -- пользователи могут удалять только свои объявления
# -- /int/ - id объявления
DELETE  {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 2c071f6b49703258910158cbe0699a8c2bdf4acf
